### PR TITLE
add cve scanning

### PR DESCRIPTION
**Pull request by Benjamintf1**

### CODE REVIEW

**Review by moleske — APPROVED** [review]
seems ok.  Didn't realize that the scanning tool can work with non-bosh release based repositories

**Comment by Benjamintf1** [comment]
I wasn't sure if it would, but i figured it didn't hurt to check. Seems like it works fine. In fact we're actually getting data(like, 1 vuln) back from it vs the release which is getting nothing.

**Comment by moleske** [comment]
probably cause the pipeline is scanning the main branch, not v8 or v7 branch.  We don't cut releases and I recently reopened dependabot bumps that were closed on main so that the main dependencies actually match what's in v8

**Comment by moleske** [comment]
might inspire me to take a look again at capi and have it just scan cloud_controller_ng rather than everything

**Comment by Benjamintf1** [comment]
Good call, let me edit the pipeline.

**Comment by Benjamintf1** [comment]
I mostly say scanning the release seems pointless because the *only* thing in the release is compiled cli's and I'm not convinced it's scanning the cli's correctly right now.

**Pull request closed without merging**
